# Generated by Codex on 2026-03-15
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0020_enforce_unique_email_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(
                max_length=255,
                help_text='Your specific area in Homabay, e.g., Ndhiwa, Rodi Kopany'
            ),
        ),
    ]
