# Generated by Django 6.0.3 on 2026-03-16 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_contact_change_counts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
