# Generated by Codex on 2026-03-13
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0002_payouts'),
        ('storefront', '0004_add_mpesa_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateSubscriptionCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(choices=[('subscription', 'Subscription'), ('bonus', 'Bonus')], default='subscription', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_commissions', to='affiliates.affiliateprofile')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_subscription_commission', to='storefront.MpesaPayment')),
                ('referred_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_subscription_referrals', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_commissions', to='storefront.subscription')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='affiliatepayout',
            name='mpesa_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='affiliatepayout',
            name='mpesa_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='affiliatepayout',
            name='mpesa_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='affiliatepayout',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
