# Generated by Django 5.0.14 on 2026-02-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0034_add_dynamic_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='schema_group',
            field=models.CharField(blank=True, help_text='Optional key to group categories for shared field schemas', max_length=100),
        ),
    ]
