# Generated by Codex on 2026-03-16

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0042_order_delivery_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('video', cloudinary.models.CloudinaryField(blank=True, folder='baysoko/listing_videos/', null=True, resource_type='video')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='listings.listing')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
