version: '3.8'
services:
  web:
    build: .
    env_file: .env
    command: gunicorn baysoko.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - redis
    ports:
      - "8000:8000"

  worker:
    build: .
    env_file: .env
    command: celery -A baysoko worker --loglevel=info
    depends_on:
      - redis

  beat:
    build: .
    env_file: .env
    command: celery -A baysoko beat --loglevel=info
    depends_on:
      - redis

  redis:
    image: redis:7
    restart: unless-stopped
