# Generated by Django 5.0.14 on 2026-02-22 12:25

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_remove_message_attachments_conversation_archived_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
