# Generated by Codex on 2026-03-16

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0022_store_location_coords'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', cloudinary.models.CloudinaryField(blank=True, folder='baysoko/stores/videos/', null=True, resource_type='video')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='storefront.store')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
