# Generated by Codex on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0023_storevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='storevideo',
            name='comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storevideo',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storevideo',
            name='shares_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storevideo',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
